# fn

A collection of functions that can be deployed and scaled at 0-N-0 using riff

=== Prerequisites

You need:

* A working Go environment
* A local 1.7+ Kubernetes cluster
* A docker daemon

=== To start minikube

[source, bash]
----
minikube start --memory=4096
----

To build images with docker in minikube use

[source, bash]
----
eval $(minikube docker-env)
----

=== Get the main riff repo and install the CLI

[source, bash]
----
go get github.com/projectriff/riff
----

=== Build the riff core components

[source, bash]
----
cd $(go env GOPATH)/src/github.com/projectriff/riff
make dockerize
----

=== Setup for development

If you want to quickly standup a development copy of Riff:

[source, bash]
----
make dev-setup
----

Which will:

* Create a `riff-system` namespace
* Deploy a non-replicated Kafka broker
* Install Riff CRDs and system components


=== To view minikube dashboard in your default browser

[source, bash]
----
minikube dashboard
----

=== compile the Java code and build the JAR

```
cd fn
```

```
./gradlew build
```

=== Install java invokers

```
riff invokers apply -f https://github.com/projectriff/java-function-invoker/raw/master/java-invoker.yaml
```

=== create the function and its input topic

```
riff create java --artifact build/libs/fn-1.0-SNAPSHOT.jar --handler functions.Hello --input words
```

=== publish a message and wait for a reply

```
riff publish --input words --data mydata --reply
```

=== Or publish message to http-gateway and wait for a reply

```
curl http://{{host}}:{{port}}/requests/words -d mydata
```

=== create another function and its input topic and set force to overwrite earlier function

```
riff create java --artifact build/libs/fn-1.0-SNAPSHOT.jar --handler functions.Length --input str --force
```

=== publish a message and wait for a reply

```
riff publish --input str --data mydata --reply
```

=== delete the function and its input topic

```
riff delete --all
```

=== To tear it all down

You can destroy everything created above by running:

[source, bash]
----
cd $(go env GOPATH)/src/github.com/projectriff/riff
make teardown
----

=== To stop minikube

[source, bash]
----
minikube stop
----